name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    - run: go build .
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo Should be deploying